# Windows env overrides (MISE_ENV=windows).
# Requires: VS 2022 C++ Desktop workload, Developer PowerShell for VS

[env]
_.path = []
CC = "cl"
CXX = "cl"
CPPFLAGS = ""
LDFLAGS = ""
CPM_SOURCE_CACHE = "{{ env.USERPROFILE }}/.cache/CPM"
CMAKE_C_COMPILER_LAUNCHER = "ccache"
CMAKE_CXX_COMPILER_LAUNCHER = "ccache"
