# FabricBehaviorTree.cmake - Fetch and configure BehaviorTree.CPP v4

set(BTCPP_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(BTCPP_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(BTCPP_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BTCPP_GROOT_INTERFACE OFF CACHE BOOL "" FORCE)
set(BTCPP_SQLITE_LOGGING OFF CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)

CPMAddPackage(
    NAME behaviortree_cpp
    GITHUB_REPOSITORY BehaviorTree/BehaviorTree.CPP
    GIT_TAG 4.8.4
    SYSTEM
    EXCLUDE_FROM_ALL
)
